// Creates two queues, one for each type of client.
Queue consumerQueue = new Queue();        
Queue corporationQueue = new Queue();
Sink sinkConsumer = new Sink("Sink Consumer"); 
Sink sinkCorporate = new Sink("Sink Corporate");
System.out.println("Starting shift 1");
Shift shift1 = new Shift(consumerQueue, corporationQueue, sinkConsumer, sinkCorporate, 5, 4, 0);
shift1.CreateConsumerOperators();
shift1.CreateCorporationOperators();
int consumerCostShift1 = shift1.getShiftCostConsumer();   
int corporateCostShift1 = shift1.getShiftCostCorporate();    
shift1.Start(); 
System.out.println("Ending shift 1");

System.out.println("Starting shift 2"); 
Shift shift2 = new Shift(consumerQueue, corporationQueue, sinkConsumer, sinkCorporate, 5,3, 8*60*60); 
shift2.CreateConsumerOperators();   
shift2.CreateCorporationOperators();     
shift2.Start();    
int consumerCostShift2 =  shift2.getShiftCostConsumer(); 
int corporateCostShift2 = shift2.getShiftCostCorporate();   
System.out.println("Ending shift 2");
System.out.println("Starting shift 3");  
Shift shift3 = new Shift(consumerQueue, corporationQueue, sinkConsumer, sinkCorporate,5,2, 16*60*60); 
shift3.CreateConsumerOperators();   
shift3.CreateCorporationOperators();    
int consumerCostShift3 = shift3.getShiftCostConsumer(); 
int corporateCostShift3 = shift3.getShiftCostCorporate(); 
shift3.Start();
System.out.println("Ending shift 3");
int consumerCostDaily = consumerCostShift1+consumerCostShift2+consumerCostShift3;
int corporateCostDaily = corporateCostShift1+corporateCostShift2+corporateCostShift3;  
System.out.println("Consumer Operator cost per day : €" + consumerCostDaily);   
System.out.println("Corporate Operator cost per day : €" + corporateCostDaily);
String csvFileCreation = "consumerDataFileCreation.csv";  
String csvFileStarted = "consumerDataFileStarted.csv"; 
String csvFileCompleted = "consumerDataFileCompleted.csv";
String csvFileCreationCorp = "corporateDataFileCreation.csv";    
String csvFileStartedCorp = "corporateDataFileStarted.csv"; 
String csvFileCompletedCorp = "corporateDataFileCompleted.csv";
CSVUtils.writeCSV(sinkConsumer,csvFileCreation, csvFileStarted, csvFileCompleted );  
CSVUtils.writeCSV(sinkCorporate,csvFileCreationCorp, csvFileStartedCorp, csvFileCompletedCorp );